name: CI
on: [push, pull_request]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
    # see https://hexdocs.pm/elixir/compatibility-and-deprecations.html#between-elixir-and-erlang-otp
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.18.x
            otp: 27.x
            lint: true
          - elixir: 1.17.x
            otp: 27.x
          - elixir: 1.17.x
            otp: 25.x
          - elixir: 1.16.x
            otp: 26.x
          - elixir: 1.16.x
            otp: 24.x
          - elixir: 1.15.x
            otp: 26.x
          - elixir: 1.15.x
            otp: 24.x
          - elixir: 1.14.x
            otp: 25.x
          - elixir: 1.14.x
            otp: 23.x
          - elixir: 1.13.x
            otp: 24.x
          - elixir: 1.13.x
            otp: 22.x
          - elixir: 1.12.x
            otp: 24.x
          - elixir: 1.12.x
            otp: 22.x
          - elixir: 1.11.x
            otp: 23.x
          - elixir: 1.11.x
            otp: 21.x
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile --warnings-as-errors
        if: ${{ matrix.lint }}
      - run: mix format --check-formatted
        if: ${{ matrix.lint }}
      - run: mix deps.unlock --check-unused
        if: ${{ matrix.lint }}
      - run: mix test
